channels:
- defaults
dependencies:
# renovate: datasource=conda depName=main/python
- python=3.14.2
# renovate: datasource=conda depName=main/pip
- pip=26.0.1
# renovate: datasource=conda depName=main/pyyaml
- pyyaml=6.0.3
# renovate: datasource=conda depName=main/mypy
- mypy=1.17.1
# renovate: datasource=conda depName=main/pytest
- pytest=9.0.2
# renovate: datasource=conda depName=main/pytest-cov
- pytest-cov=7.0.0
# renovate: datasource=conda depName=main/pytest-mock
- pytest-mock=3.15.1
- pip:
  # renovate: datasource=pypi
  - cogapp==3.6.0
  - -e .
